# Generated by Django 5.1.3 on 2024-11-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('photo', models.ImageField(upload_to='backgrounds')),
                ('photo_hover', models.ImageField(default='backgrounds/default.png', upload_to='backgrounds')),
                ('photo_vn', models.ImageField(default='backgrounds/default.png', upload_to='backgrounds')),
                ('photo_vn_hover', models.ImageField(default='backgrounds/default.png', upload_to='backgrounds')),
                ('photo_kr', models.ImageField(default='backgrounds/default.png', upload_to='backgrounds')),
                ('photo_kr_hover', models.ImageField(default='backgrounds/default.png', upload_to='backgrounds')),
                ('position', models.TextField(default='center')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
