# Generated by Django 5.1.3 on 2024-11-06 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('background', '0001_initial'),
        ('frame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('photo', models.ImageField(upload_to='layouts')),
                ('photo_cover', models.ImageField(default='layouts/default.png', upload_to='layouts')),
                ('photo_full', models.ImageField(default='layouts/default.png', upload_to='layouts')),
                ('position', models.TextField(default='center')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.background')),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frame.frame')),
            ],
        ),
    ]
