# Generated by Django 5.1.3 on 2024-11-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.TextField()),
                ('name', models.TextField()),
                ('code', models.TextField(default='zalopay', unique=True)),
                ('appID', models.TextField(default='2553')),
                ('key1', models.TextField(default='PcY4iZIKFCIdgZvA6ueMcMHHUbRLYjPL')),
                ('key2', models.TextField(default='kLtgPl8HHhfvMuDHPwKfgfsY4Ydm9eIz')),
                ('endpoint_sandbox', models.TextField(default='https://sb-openapi.zalopay.vn/v2/create')),
                ('endpoint_prod', models.TextField(default='https://openapi.zalopay.vn/v2/create')),
                ('token', models.TextField(default='123')),
                ('username', models.TextField(default='account-demo')),
                ('password', models.TextField(default='123')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
